version: '3.5'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    user: 1000:1000
    volumes:
      - .:/opt/apolloapi
    command: sh -c "yarn --production=false && yarn dev"
    environment:
      NODE_ENV: 'development'
    ports:
      - '5000:5000'
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    user: 1000:1000
    volumes:
      - ./apolloui:/app
    command: sh -c "npm start"
    environment:
      NODE_ENV: 'development'
    ports:
      - '3000:3000'
